<a href="https://colab.research.google.com/github/limyerin/contest/blob/main/data_tidy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#테스트

In [1]:
from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
data= pd.read_excel("/content/drive/MyDrive/data/data1.xlsx",engine='openpyxl')
data

,ind,y19,y20,y21,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,귀농귀촌 온라인 교육 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,NaN,교육이수여부_
1,귀농귀촌 온라인 교육 이수여부_이수 (%),21.5,20.5,24.2,NaN,NaN,NaN
2,귀농귀촌 온라인 교육 이수여부_이수하지 않음 (%),78.5,79.5,75.8,NaN,NaN,NaN
3,귀농귀촌 오프라인 교육 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,NaN,NaN
4,귀농귀촌 오프라인 교육 이수여부_이수 (%),56.6,43.8,42.5,NaN,NaN,NaN
5,귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (%),43.4,56.2,57.5,NaN,NaN,NaN
6,귀농귀촌 인턴십 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,NaN,NaN
7,귀농귀촌 인턴십 이수여부_이수 (%),14.9,11.2,16.8,NaN,NaN,NaN
8,귀농귀촌 인턴십 이수여부_이수하지 않음 (%),85.1,88.8,83.2,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,귀농귀촌교육개선점_사례수 (명),2086.0,2028.0,3000.0,NaN,NaN,귀농귀촌교육개선점_
11,귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (%),43.2,43.8,40.5,NaN,NaN,NaN
12,귀농귀촌교육개선점_수준별 강좌 개설 (%),15.4,16.6,20.1,NaN,NaN,NaN
13,귀농귀촌교육개선점_강사의 전문성 증대 (%),4.5,7.4,8.3,NaN,NaN,NaN
14,귀농귀촌교육개선점_교육 비용 지원 (%),6.2,3.8,4.9,NaN,NaN,NaN
15,귀농귀촌교육개선점_현장 실습 연계 강화 (%),11.3,10.7,8.4,NaN,NaN,NaN
16,귀농귀촌교육개선점_교육 시간대 다양화 (%),6.5,5.0,5.3,NaN,NaN,NaN
17,귀농귀촌교육개선점_지리적 접근성 확대 (%),6.5,6.8,6.7,NaN,NaN,NaN
18,귀농귀촌교육개선점_온라인 교육 확대 (%),4.9,4.8,5.9,NaN,NaN,NaN
19,귀농귀촌교육개선점_기타 (%),0.3,0.0,0.0,NaN,NaN,NaN
20,귀농귀촌교육개선점_없음 (%),0.9,0.8,-,NaN,NaN,NaN
21,귀농귀촌교육개선점_모름/무응답 (%),0.4,0.3,-,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,귀농귀촌교육강화점_사례수 (명),2086.0,2028.0,3000.0,NaN,NaN,귀농귀촌교육강화점_
24,귀농귀촌교육강화점_주거 및 전원생활 (%),26.6,32.6,28.9,NaN,NaN,NaN
25,귀농귀촌교육강화점_귀촌창업 (%),11.9,7.7,11.1,NaN,NaN,NaN
26,귀농귀촌교육강화점_관계형성 (%),12.1,14.5,20.5,NaN,NaN,NaN
27,귀농귀촌교육강화점_텃밭 가꾸기 (%),9.4,8.9,11.6,NaN,NaN,NaN
28,귀농귀촌교육강화점_영농교육 (%),8.1,8.2,6.9,NaN,NaN,NaN
29,귀농귀촌교육강화점_농업농촌의 이해(기초소양) (%),9.7,7.3,6.8,NaN,NaN,NaN
30,"귀농귀촌교육강화점_제도,정책 (%)",20.9,19.1,14.2,NaN,NaN,NaN
31,귀농귀촌교육강화점_기타 (%),0.2,0.1,0.0,NaN,NaN,NaN
32,귀농귀촌교육강화점_없음 (%),0.8,1.3,-,NaN,NaN,NaN
33,귀농귀촌교육강화점_모름/무응답 (%),0.3,0.3,-,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,교육받지않이유_사례수 (명),1645.0,1704.0,2759.0,NaN,NaN,교육받지않이유_
36,교육받지않이유_교육에 대해 알지 못해서 (%),51.4,43.2,34.6,NaN,NaN,NaN
37,교육받지않이유_시간이 없어서 (%),20.9,26.4,26.5,NaN,NaN,NaN
38,"교육받지않이유_적합한 과정(작목, 과목)이 없어 (%)",11.4,8.8,14.9,NaN,NaN,NaN
39,교육받지않이유_내용이 도움이 되지 않아서 (%),13.7,20.0,23.1,NaN,NaN,NaN
40,교육받지않이유_교육비용 때문에 (%),0.5,0.1,0.8,NaN,NaN,NaN
41,교육받지않이유_기타 (%),1.6,1.0,0.0,NaN,NaN,NaN
42,교육받지않이유_없음 (%),0.6,0.4,-,NaN,NaN,NaN
43,교육받지않이유_모름/무응답 (%),0.0,-,-,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,교육실제도움정도_사례수 (명),441.0,324.0,241.0,NaN,NaN,교육실제도움정도_
46,교육실제도움정도_전혀 도움 안됨 (%),0.6,0.4,0.0,NaN,NaN,NaN
47,교육실제도움정도_도움 안됨 (%),5.1,3.1,0.8,NaN,NaN,NaN
48,교육실제도움정도_보통 (%),22.6,23.4,13.4,NaN,NaN,NaN
49,교육실제도움정도_도움 됨 (%),65.3,70.3,80.9,NaN,NaN,NaN
50,교육실제도움정도_매우 도움 됨 (%),6.4,2.6,4.9,NaN,NaN,NaN

In [3]:
data1=data.set_index("ind")
data1.columns

Index(['y19', 'y20', 'y21', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'], dtype='object')

In [4]:
data1.drop(['Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'],axis=1,inplace=True)

In [5]:
data1

                                   y19     y20     y21
ind
귀농귀촌 온라인 교육 이수여부_사례수 (명)        2081.0  2038.0  3000.0
귀농귀촌 온라인 교육 이수여부_이수 (%)           21.5    20.5    24.2
귀농귀촌 온라인 교육 이수여부_이수하지 않음 (%)      78.5    79.5    75.8
귀농귀촌 오프라인 교육 이수여부_사례수 (명)       2081.0  2038.0  3000.0
귀농귀촌 오프라인 교육 이수여부_이수 (%)          56.6    43.8    42.5
귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (%)     43.4    56.2    57.5
귀농귀촌 인턴십 이수여부_사례수 (명)           2081.0  2038.0  3000.0
귀농귀촌 인턴십 이수여부_이수 (%)              14.9    11.2    16.8
귀농귀촌 인턴십 이수여부_이수하지 않음 (%)         85.1    88.8    83.2
NaN                                NaN     NaN     NaN
귀농귀촌교육개선점_사례수 (명)               2086.0  2028.0  3000.0
귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (%)       43.2    43.8    40.5
귀농귀촌교육개선점_수준별 강좌 개설 (%)           15.4    16.6    20.1
귀농귀촌교육개선점_강사의 전문성 증대 (%)           4.5     7.4     8.3
귀농귀촌교육개선점_교육 비용 지원 (%)             6.2     3.8     4.9
귀농귀촌교육개선점_현장 실습 연계 강화 (%)         11.3    10.7     8.4
귀농귀촌교육개선점_교육 시간대 다양화 (%)           6.5     5.0     5.3
귀농귀촌교육개선점_지리적 접근성 확대 (%)           6.5     6.8     6.7
귀농귀촌교육개선점_온라인 교육 확대 (%)            4.9     4.8     5.9
귀농귀촌교육개선점_기타 (%)                   0.3     0.0     0.0
귀농귀촌교육개선점_없음 (%)                   0.9     0.8       -
귀농귀촌교육개선점_모름/무응답 (%)               0.4     0.3       -
NaN                                NaN     NaN     NaN
귀농귀촌교육강화점_사례수 (명)               2086.0  2028.0  3000.0
귀농귀촌교육강화점_주거 및 전원생활 (%)           26.6    32.6    28.9
귀농귀촌교육강화점_귀촌창업 (%)                11.9     7.7    11.1
귀농귀촌교육강화점_관계형성 (%)                12.1    14.5    20.5
귀농귀촌교육강화점_텃밭 가꾸기 (%)               9.4     8.9    11.6
귀농귀촌교육강화점_영농교육 (%)                 8.1     8.2     6.9
귀농귀촌교육강화점_농업농촌의 이해(기초소양) (%)       9.7     7.3     6.8
귀농귀촌교육강화점_제도,정책 (%)               20.9    19.1    14.2
귀농귀촌교육강화점_기타 (%)                   0.2     0.1     0.0
귀농귀촌교육강화점_없음 (%)                   0.8     1.3       -
귀농귀촌교육강화점_모름/무응답 (%)               0.3     0.3       -
NaN                                NaN     NaN     NaN
교육받지않이유_사례수 (명)                 1645.0  1704.0  2759.0
교육받지않이유_교육에 대해 알지 못해서 (%)         51.4    43.2    34.6
교육받지않이유_시간이 없어서 (%)               20.9    26.4    26.5
교육받지않이유_적합한 과정(작목, 과목)이 없어 (%)    11.4     8.8    14.9
교육받지않이유_내용이 도움이 되지 않아서 (%)        13.7    20.0    23.1
교육받지않이유_교육비용 때문에 (%)               0.5     0.1     0.8
교육받지않이유_기타 (%)                     1.6     1.0     0.0
교육받지않이유_없음 (%)                     0.6     0.4       -
교육받지않이유_모름/무응답 (%)                 0.0       -       -
NaN                                NaN     NaN     NaN
교육실제도움정도_사례수 (명)                 441.0   324.0   241.0
교육실제도움정도_전혀 도움 안됨 (%)              0.6     0.4     0.0
교육실제도움정도_도움 안됨 (%)                 5.1     3.1     0.8
교육실제도움정도_보통 (%)                   22.6    23.4    13.4
교육실제도움정도_도움 됨 (%)                 65.3    70.3    80.9
교육실제도움정도_매우 도움 됨 (%)               6.4     2.6     4.9

In [6]:
data1['y19']

ind
귀농귀촌 온라인 교육 이수여부_사례수 (명)          2081.0
귀농귀촌 온라인 교육 이수여부_이수 (%)             21.5
귀농귀촌 온라인 교육 이수여부_이수하지 않음 (%)        78.5
귀농귀촌 오프라인 교육 이수여부_사례수 (명)         2081.0
귀농귀촌 오프라인 교육 이수여부_이수 (%)            56.6
귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (%)       43.4
귀농귀촌 인턴십 이수여부_사례수 (명)             2081.0
귀농귀촌 인턴십 이수여부_이수 (%)                14.9
귀농귀촌 인턴십 이수여부_이수하지 않음 (%)           85.1
NaN                                  NaN
귀농귀촌교육개선점_사례수 (명)                 2086.0
귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (%)         43.2
귀농귀촌교육개선점_수준별 강좌 개설 (%)             15.4
귀농귀촌교육개선점_강사의 전문성 증대 (%)             4.5
귀농귀촌교육개선점_교육 비용 지원 (%)               6.2
귀농귀촌교육개선점_현장 실습 연계 강화 (%)           11.3
귀농귀촌교육개선점_교육 시간대 다양화 (%)             6.5
귀농귀촌교육개선점_지리적 접근성 확대 (%)             6.5
귀농귀촌교육개선점_온라인 교육 확대 (%)              4.9
귀농귀촌교육개선점_기타 (%)                     0.3
귀농귀촌교육개선점_없음 (%)                     0.9
귀농귀촌교육개선점_모름/무응답 (%)                 0.4
NaN                                  NaN
귀농귀촌교육강화점_사례수 (명)                 2086.0
귀농귀촌교육강화점_주거 및 전원생활 (%)             26.6
귀농귀촌교육강화점_귀촌창업 (%)                  11.9
귀농귀촌교육강화점_관계형성 (%)                  12.1
귀농귀촌교육강화점_텃밭 가꾸기 (%)                 9.4
귀농귀촌교육강화점_영농교육 (%)                   8.1
귀농귀촌교육강화점_농업농촌의 이해(기초소양) (%)         9.7
귀농귀촌교육강화점_제도,정책 (%)                 20.9
귀농귀촌교육강화점_기타 (%)                     0.2
귀농귀촌교육강화점_없음 (%)                     0.8
귀농귀촌교육강화점_모름/무응답 (%)                 0.3
NaN                                  NaN
교육받지않이유_사례수 (명)                   1645.0
교육받지않이유_교육에 대해 알지 못해서 (%)           51.4
교육받지않이유_시간이 없어서 (%)                 20.9
교육받지않이유_적합한 과정(작목, 과목)이 없어 (%)      11.4
교육받지않이유_내용이 도움이 되지 않아서 (%)          13.7
교육받지않이유_교육비용 때문에 (%)                 0.5
교육받지않이유_기타 (%)                       1.6
교육받지않이유_없음 (%)                       0.6
교육받지않이유_모름/무응답 (%)                   0.0
NaN                                  NaN
교육실제도움정도_사례수 (명)                   441.0
교육실제도움정도_전혀 도움 안됨 (%)                0.6
교육실제도움정도_도움 안됨 (%)                   5.1
교육실제도움정도_보통 (%)                     22.6
교육실제도움정도_도움 됨 (%)                   65.3
교육실제도움정도_매우 도움 됨 (%)                 6.4
Name: y19, dtype: float64

In [7]:
len(data1[:]['y19'])

51

In [8]:
data[0:1]['y19']

0    2081.0
Name: y19, dtype: float64

- 파일마다 교육 이수자수가 다름
- 퍼센트로 결과가 나와있음
- 실제 명수로 계산

[아래 코드]

100이상이면 사례수(명)으로 파악해서 백분율(100이하) 와 곱해주는 반복문 만들려고 시도.
반복문 진행하다가 다시 100이상의 수를 만나면 다시 곱해서 구하는 방식 생각.

In [ ]:
for i in range(1,51):
  if (data1[i-1:i]['y19']>=100):
    j=i
    n=0
    while((data1[j:j+1]['y19']<100) == True) :
      n+=1
      re= data1[i-1:i]['y19']*(data1[j:j+1]['y19'])
      data1.replace(data1[j:j+1]['y19'], re)
      j+=1
    
    i+=n

  if (data1[i-1:i]['y19'] == np.NaN):
      pass

  else:
      pass

ValueError: ignored

In [ ]:
for i in range(1,51):
  i+=1
  print(i)
  while (data1[i-1:i]['y19']>=100):
    print(data1[i-1:i]['y19'])

2

ValueError: ignored

AttributeError: ignored

[위 코드 에러]

엑셀로 계산해 얻은 사람 데이터 정리

In [9]:
pdata= pd.read_excel("/content/drive/MyDrive/data/data_person.xlsx",engine='openpyxl')
pdata

,ind,y19,y20,y21,Unnamed: 4,Ind,Y19,Y20,Y21
0,귀농귀촌 온라인 교육 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,귀농귀촌 온라인 교육 이수여부_사례수 (명),2081.000,2038.0,3000.0
1,귀농귀촌 온라인 교육 이수여부_이수 (%),21.5,20.5,24.2,NaN,귀농귀촌 온라인 교육 이수여부_이수 (명),447.415,417.79,726
2,귀농귀촌 온라인 교육 이수여부_이수하지 않음 (%),78.5,79.5,75.8,NaN,귀농귀촌 온라인 교육 이수여부_이수하지 않음 (명),1633.585,1620.21,2274
3,귀농귀촌 오프라인 교육 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,귀농귀촌 오프라인 교육 이수여부_사례수 (명),2081.000,2038.0,3000.0
4,귀농귀촌 오프라인 교육 이수여부_이수 (%),56.6,43.8,42.5,NaN,귀농귀촌 오프라인 교육 이수여부_이수 (명),1177.846,892.644,1275
5,귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (%),43.4,56.2,57.5,NaN,귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (명),903.154,1145.356,1725
6,귀농귀촌 인턴십 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,귀농귀촌 인턴십 이수여부_사례수 (명),2081.000,2038.0,3000.0
7,귀농귀촌 인턴십 이수여부_이수 (%),14.9,11.2,16.8,NaN,귀농귀촌 인턴십 이수여부_이수 (명),310.069,228.256,504
8,귀농귀촌 인턴십 이수여부_이수하지 않음 (%),85.1,88.8,83.2,NaN,귀농귀촌 인턴십 이수여부_이수하지 않음 (명),1770.931,1809.744,2496
9,귀농귀촌교육개선점_사례수 (명),2086.0,2028.0,3000.0,NaN,귀농귀촌교육개선점_사례수 (명),2086.000,2028.0,3000.0
10,귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (%),43.2,43.8,40.5,NaN,귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (명),888.264,888.264,1215
11,귀농귀촌교육개선점_수준별 강좌 개설 (%),15.4,16.6,20.1,NaN,귀농귀촌교육개선점_수준별 강좌 개설 (명),321.244,336.648,603
12,귀농귀촌교육개선점_강사의 전문성 증대 (%),4.5,7.4,8.3,NaN,귀농귀촌교육개선점_강사의 전문성 증대 (명),93.870,150.072,249
13,귀농귀촌교육개선점_교육 비용 지원 (%),6.2,3.8,4.9,NaN,귀농귀촌교육개선점_교육 비용 지원 (명),129.332,77.064,147
14,귀농귀촌교육개선점_현장 실습 연계 강화 (%),11.3,10.7,8.4,NaN,귀농귀촌교육개선점_현장 실습 연계 강화 (명),235.718,216.996,252
15,귀농귀촌교육개선점_교육 시간대 다양화 (%),6.5,5.0,5.3,NaN,귀농귀촌교육개선점_교육 시간대 다양화 (명),135.590,101.4,159
16,귀농귀촌교육개선점_지리적 접근성 확대 (%),6.5,6.8,6.7,NaN,귀농귀촌교육개선점_지리적 접근성 확대 (명),135.590,137.904,201
17,귀농귀촌교육개선점_온라인 교육 확대 (%),4.9,4.8,5.9,NaN,귀농귀촌교육개선점_온라인 교육 확대 (명),102.214,97.344,177
18,귀농귀촌교육개선점_기타 (%),0.3,0.0,0.0,NaN,귀농귀촌교육개선점_기타 (명),6.258,0,0
19,귀농귀촌교육개선점_없음 (%),0.9,0.8,-,NaN,귀농귀촌교육개선점_없음 (명),18.774,16.224,#VALUE!
20,귀농귀촌교육개선점_모름/무응답 (%),0.4,0.3,-,NaN,귀농귀촌교육개선점_모름/무응답 (명),8.344,6.084,#VALUE!
21,귀농귀촌교육강화점_사례수 (명),2086.0,2028.0,3000.0,NaN,귀농귀촌교육강화점_사례수 (명),2086.000,2028.0,3000.0
22,귀농귀촌교육강화점_주거 및 전원생활 (%),26.6,32.6,28.9,NaN,귀농귀촌교육강화점_주거 및 전원생활 (명),554.876,661.128,867
23,귀농귀촌교육강화점_귀촌창업 (%),11.9,7.7,11.1,NaN,귀농귀촌교육강화점_귀촌창업 (명),248.234,156.156,333
24,귀농귀촌교육강화점_관계형성 (%),12.1,14.5,20.5,NaN,귀농귀촌교육강화점_관계형성 (명),252.406,294.06,615
25,귀농귀촌교육강화점_텃밭 가꾸기 (%),9.4,8.9,11.6,NaN,귀농귀촌교육강화점_텃밭 가꾸기 (명),196.084,180.492,348
26,귀농귀촌교육강화점_영농교육 (%),8.1,8.2,6.9,NaN,귀농귀촌교육강화점_영농교육 (명),168.966,166.296,207
27,귀농귀촌교육강화점_농업농촌의 이해(기초소양) (%),9.7,7.3,6.8,NaN,귀농귀촌교육강화점_농업농촌의 이해(기초소양) (명),202.342,148.044,204
28,"귀농귀촌교육강화점_제도,정책 (%)",20.9,19.1,14.2,NaN,"귀농귀촌교육강화점_제도,정책 (명)",435.974,387.348,426
29,귀농귀촌교육강화점_기타 (%),0.2,0.1,0.0,NaN,귀농귀촌교육강화점_기타 (명),4.172,2.028,0
30,귀농귀촌교육강화점_없음 (%),0.8,1.3,-,NaN,귀농귀촌교육강화점_없음 (명),16.688,26.364,#VALUE!
31,귀농귀촌교육강화점_모름/무응답 (%),0.3,0.3,-,NaN,귀농귀촌교육강화점_모름/무응답 (명),6.258,6.084,#VALUE!
32,교육받지않이유_사례수 (명),1645.0,1704.0,2759.0,NaN,교육받지않이유_사례수 (명),1645.000,1704.0,2759.0
33,교육받지않이유_교육에 대해 알지 못해서 (%),51.4,43.2,34.6,NaN,교육받지않이유_교육에 대해 알지 못해서 (명),845.530,736.128,954.614
34,교육받지않이유_시간이 없어서 (%),20.9,26.4,26.5,NaN,교육받지않이유_시간이 없어서 (명),343.805,449.856,731.135
35,"교육받지않이유_적합한 과정(작목, 과목)이 없어 (%)",11.4,8.8,14.9,NaN,"교육받지않이유_적합한 과정(작목, 과목)이 없어 (명)",187.530,149.952,411.091
36,교육받지않이유_내용이 도움이 되지 않아서 (%),13.7,20.0,23.1,NaN,교육받지않이유_내용이 도움이 되지 않아서 (명),225.365,340.8,637.329
37,교육받지않이유_교육비용 때문에 (%),0.5,0.1,0.8,NaN,교육받지않이유_교육비용 때문에 (명),8.225,1.704,22.072
38,교육받지않이유_기타 (%),1.6,1.0,0.0,NaN,교육받지않이유_기타 (명),26.320,17.04,0
39,교육받지않이유_없음 (%),0.6,0.4,-,NaN,교육받지않이유_없음 (명),9.870,6.816,#VALUE!
40,교육받지않이유_모름/무응답 (%),0.0,-,-,NaN,교육받지않이유_모름/무응답 (명),0.000,#VALUE!,#VALUE!
41,교육실제도움정도_사례수 (명),441.0,324.0,241.0,NaN,교육실제도움정도_사례수 (명),441.000,324.0,241.0
42,교육실제도움정도_전혀 도움 안됨 (%),0.6,0.4,0.0,NaN,교육실제도움정도_전혀 도움 안됨 (명),2.646,1.296,0
43,교육실제도움정도_도움 안됨 (%),5.1,3.1,0.8,NaN,교육실제도움정도_도움 안됨 (명),22.491,10.044,1.928
44,교육실제도움정도_보통 (%),22.6,23.4,13.4,NaN,교육실제도움정도_보통 (명),99.666,75.816,32.294
45,교육실제도움정도_도움 됨 (%),65.3,70.3,80.9,NaN,교육실제도움정도_도움 됨 (명),287.973,227.772,194.969
46,교육실제도움정도_매우 도움 됨 (%),6.4,2.6,4.9,NaN,교육실제도움정도_매우 도움 됨 (명),28.224,8.424,11.809

In [10]:
# pdata의 컬럼 불러오기
pdata.columns

Index(['ind', 'y19', 'y20', 'y21', 'Unnamed: 4', 'Ind', 'Y19', 'Y20', 'Y21'], dtype='object')

In [11]:
# 'ind', 'y19', 'y20', 'y21', 'Unnamed: 4' 컬럼 제거
pdata2= pdata.drop(['ind', 'y19', 'y20', 'y21', 'Unnamed: 4'],axis=1,inplace=True)
pdata2

In [18]:
pdata

                               Ind       Y19       Y20      Y21
0         귀농귀촌 온라인 교육 이수여부_사례수 (명)  2081.000    2038.0   3000.0
1          귀농귀촌 온라인 교육 이수여부_이수 (명)   447.415    417.79      726
2     귀농귀촌 온라인 교육 이수여부_이수하지 않음 (명)  1633.585   1620.21     2274
3        귀농귀촌 오프라인 교육 이수여부_사례수 (명)  2081.000    2038.0   3000.0
4         귀농귀촌 오프라인 교육 이수여부_이수 (명)  1177.846   892.644     1275
5    귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (명)   903.154  1145.356     1725
6            귀농귀촌 인턴십 이수여부_사례수 (명)  2081.000    2038.0   3000.0
7             귀농귀촌 인턴십 이수여부_이수 (명)   310.069   228.256      504
8        귀농귀촌 인턴십 이수여부_이수하지 않음 (명)  1770.931  1809.744     2496
9                귀농귀촌교육개선점_사례수 (명)  2086.000    2028.0   3000.0
10     귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (명)   888.264   888.264     1215
11         귀농귀촌교육개선점_수준별 강좌 개설 (명)   321.244   336.648      603
12        귀농귀촌교육개선점_강사의 전문성 증대 (명)    93.870   150.072      249
13          귀농귀촌교육개선점_교육 비용 지원 (명)   129.332    77.064      147
14       귀농귀촌교육개선점_현장 실습 연계 강화 (명)   235.718   216.996      252
15        귀농귀촌교육개선점_교육 시간대 다양화 (명)   135.590     101.4      159
16        귀농귀촌교육개선점_지리적 접근성 확대 (명)   135.590   137.904      201
17         귀농귀촌교육개선점_온라인 교육 확대 (명)   102.214    97.344      177
18                귀농귀촌교육개선점_기타 (명)     6.258         0        0
19                귀농귀촌교육개선점_없음 (명)    18.774    16.224  #VALUE!
20            귀농귀촌교육개선점_모름/무응답 (명)     8.344     6.084  #VALUE!
21               귀농귀촌교육강화점_사례수 (명)  2086.000    2028.0   3000.0
22         귀농귀촌교육강화점_주거 및 전원생활 (명)   554.876   661.128      867
23              귀농귀촌교육강화점_귀촌창업 (명)   248.234   156.156      333
24              귀농귀촌교육강화점_관계형성 (명)   252.406    294.06      615
25            귀농귀촌교육강화점_텃밭 가꾸기 (명)   196.084   180.492      348
26              귀농귀촌교육강화점_영농교육 (명)   168.966   166.296      207
27    귀농귀촌교육강화점_농업농촌의 이해(기초소양) (명)   202.342   148.044      204
28             귀농귀촌교육강화점_제도,정책 (명)   435.974   387.348      426
29                귀농귀촌교육강화점_기타 (명)     4.172     2.028        0
30                귀농귀촌교육강화점_없음 (명)    16.688    26.364  #VALUE!
31            귀농귀촌교육강화점_모름/무응답 (명)     6.258     6.084  #VALUE!
32                 교육받지않이유_사례수 (명)  1645.000    1704.0   2759.0
33       교육받지않이유_교육에 대해 알지 못해서 (명)   845.530   736.128  954.614
34             교육받지않이유_시간이 없어서 (명)   343.805   449.856  731.135
35  교육받지않이유_적합한 과정(작목, 과목)이 없어 (명)   187.530   149.952  411.091
36      교육받지않이유_내용이 도움이 되지 않아서 (명)   225.365     340.8  637.329
37            교육받지않이유_교육비용 때문에 (명)     8.225     1.704   22.072
38                  교육받지않이유_기타 (명)    26.320     17.04        0
39                  교육받지않이유_없음 (명)     9.870     6.816  #VALUE!
40              교육받지않이유_모름/무응답 (명)     0.000   #VALUE!  #VALUE!
41                교육실제도움정도_사례수 (명)   441.000     324.0    241.0
42           교육실제도움정도_전혀 도움 안됨 (명)     2.646     1.296        0
43              교육실제도움정도_도움 안됨 (명)    22.491    10.044    1.928
44                 교육실제도움정도_보통 (명)    99.666    75.816   32.294
45               교육실제도움정도_도움 됨 (명)   287.973   227.772  194.969
46            교육실제도움정도_매우 도움 됨 (명)    28.224     8.424   11.809

In [13]:
# #VALUE!-> - 바꾸기

#df = pdata.replace('#VALUE!','-')  # .... datatype이 object로 나오니 그냥 0으로 변경할 것
#df

                               Ind       Y19       Y20      Y21
0         귀농귀촌 온라인 교육 이수여부_사례수 (명)  2081.000    2038.0   3000.0
1          귀농귀촌 온라인 교육 이수여부_이수 (명)   447.415    417.79      726
2     귀농귀촌 온라인 교육 이수여부_이수하지 않음 (명)  1633.585   1620.21     2274
3        귀농귀촌 오프라인 교육 이수여부_사례수 (명)  2081.000    2038.0   3000.0
4         귀농귀촌 오프라인 교육 이수여부_이수 (명)  1177.846   892.644     1275
5    귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (명)   903.154  1145.356     1725
6            귀농귀촌 인턴십 이수여부_사례수 (명)  2081.000    2038.0   3000.0
7             귀농귀촌 인턴십 이수여부_이수 (명)   310.069   228.256      504
8        귀농귀촌 인턴십 이수여부_이수하지 않음 (명)  1770.931  1809.744     2496
9                귀농귀촌교육개선점_사례수 (명)  2086.000    2028.0   3000.0
10     귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (명)   888.264   888.264     1215
11         귀농귀촌교육개선점_수준별 강좌 개설 (명)   321.244   336.648      603
12        귀농귀촌교육개선점_강사의 전문성 증대 (명)    93.870   150.072      249
13          귀농귀촌교육개선점_교육 비용 지원 (명)   129.332    77.064      147
14       귀농귀촌교육개선점_현장 실습 연계 강화 (명)   235.718   216.996      252
15        귀농귀촌교육개선점_교육 시간대 다양화 (명)   135.590     101.4      159
16        귀농귀촌교육개선점_지리적 접근성 확대 (명)   135.590   137.904      201
17         귀농귀촌교육개선점_온라인 교육 확대 (명)   102.214    97.344      177
18                귀농귀촌교육개선점_기타 (명)     6.258         0        0
19                귀농귀촌교육개선점_없음 (명)    18.774    16.224        -
20            귀농귀촌교육개선점_모름/무응답 (명)     8.344     6.084        -
21               귀농귀촌교육강화점_사례수 (명)  2086.000    2028.0   3000.0
22         귀농귀촌교육강화점_주거 및 전원생활 (명)   554.876   661.128      867
23              귀농귀촌교육강화점_귀촌창업 (명)   248.234   156.156      333
24              귀농귀촌교육강화점_관계형성 (명)   252.406    294.06      615
25            귀농귀촌교육강화점_텃밭 가꾸기 (명)   196.084   180.492      348
26              귀농귀촌교육강화점_영농교육 (명)   168.966   166.296      207
27    귀농귀촌교육강화점_농업농촌의 이해(기초소양) (명)   202.342   148.044      204
28             귀농귀촌교육강화점_제도,정책 (명)   435.974   387.348      426
29                귀농귀촌교육강화점_기타 (명)     4.172     2.028        0
30                귀농귀촌교육강화점_없음 (명)    16.688    26.364        -
31            귀농귀촌교육강화점_모름/무응답 (명)     6.258     6.084        -
32                 교육받지않이유_사례수 (명)  1645.000    1704.0   2759.0
33       교육받지않이유_교육에 대해 알지 못해서 (명)   845.530   736.128  954.614
34             교육받지않이유_시간이 없어서 (명)   343.805   449.856  731.135
35  교육받지않이유_적합한 과정(작목, 과목)이 없어 (명)   187.530   149.952  411.091
36      교육받지않이유_내용이 도움이 되지 않아서 (명)   225.365     340.8  637.329
37            교육받지않이유_교육비용 때문에 (명)     8.225     1.704   22.072
38                  교육받지않이유_기타 (명)    26.320     17.04        0
39                  교육받지않이유_없음 (명)     9.870     6.816        -
40              교육받지않이유_모름/무응답 (명)     0.000         -        -
41                교육실제도움정도_사례수 (명)   441.000     324.0    241.0
42           교육실제도움정도_전혀 도움 안됨 (명)     2.646     1.296        0
43              교육실제도움정도_도움 안됨 (명)    22.491    10.044    1.928
44                 교육실제도움정도_보통 (명)    99.666    75.816   32.294
45               교육실제도움정도_도움 됨 (명)   287.973   227.772  194.969
46            교육실제도움정도_매우 도움 됨 (명)    28.224     8.424   11.809

In [19]:
df0 = pdata.replace('#VALUE!','0')
df0

                               Ind       Y19       Y20      Y21
0         귀농귀촌 온라인 교육 이수여부_사례수 (명)  2081.000    2038.0   3000.0
1          귀농귀촌 온라인 교육 이수여부_이수 (명)   447.415    417.79      726
2     귀농귀촌 온라인 교육 이수여부_이수하지 않음 (명)  1633.585   1620.21     2274
3        귀농귀촌 오프라인 교육 이수여부_사례수 (명)  2081.000    2038.0   3000.0
4         귀농귀촌 오프라인 교육 이수여부_이수 (명)  1177.846   892.644     1275
5    귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (명)   903.154  1145.356     1725
6            귀농귀촌 인턴십 이수여부_사례수 (명)  2081.000    2038.0   3000.0
7             귀농귀촌 인턴십 이수여부_이수 (명)   310.069   228.256      504
8        귀농귀촌 인턴십 이수여부_이수하지 않음 (명)  1770.931  1809.744     2496
9                귀농귀촌교육개선점_사례수 (명)  2086.000    2028.0   3000.0
10     귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (명)   888.264   888.264     1215
11         귀농귀촌교육개선점_수준별 강좌 개설 (명)   321.244   336.648      603
12        귀농귀촌교육개선점_강사의 전문성 증대 (명)    93.870   150.072      249
13          귀농귀촌교육개선점_교육 비용 지원 (명)   129.332    77.064      147
14       귀농귀촌교육개선점_현장 실습 연계 강화 (명)   235.718   216.996      252
15        귀농귀촌교육개선점_교육 시간대 다양화 (명)   135.590     101.4      159
16        귀농귀촌교육개선점_지리적 접근성 확대 (명)   135.590   137.904      201
17         귀농귀촌교육개선점_온라인 교육 확대 (명)   102.214    97.344      177
18                귀농귀촌교육개선점_기타 (명)     6.258         0        0
19                귀농귀촌교육개선점_없음 (명)    18.774    16.224        0
20            귀농귀촌교육개선점_모름/무응답 (명)     8.344     6.084        0
21               귀농귀촌교육강화점_사례수 (명)  2086.000    2028.0   3000.0
22         귀농귀촌교육강화점_주거 및 전원생활 (명)   554.876   661.128      867
23              귀농귀촌교육강화점_귀촌창업 (명)   248.234   156.156      333
24              귀농귀촌교육강화점_관계형성 (명)   252.406    294.06      615
25            귀농귀촌교육강화점_텃밭 가꾸기 (명)   196.084   180.492      348
26              귀농귀촌교육강화점_영농교육 (명)   168.966   166.296      207
27    귀농귀촌교육강화점_농업농촌의 이해(기초소양) (명)   202.342   148.044      204
28             귀농귀촌교육강화점_제도,정책 (명)   435.974   387.348      426
29                귀농귀촌교육강화점_기타 (명)     4.172     2.028        0
30                귀농귀촌교육강화점_없음 (명)    16.688    26.364        0
31            귀농귀촌교육강화점_모름/무응답 (명)     6.258     6.084        0
32                 교육받지않이유_사례수 (명)  1645.000    1704.0   2759.0
33       교육받지않이유_교육에 대해 알지 못해서 (명)   845.530   736.128  954.614
34             교육받지않이유_시간이 없어서 (명)   343.805   449.856  731.135
35  교육받지않이유_적합한 과정(작목, 과목)이 없어 (명)   187.530   149.952  411.091
36      교육받지않이유_내용이 도움이 되지 않아서 (명)   225.365     340.8  637.329
37            교육받지않이유_교육비용 때문에 (명)     8.225     1.704   22.072
38                  교육받지않이유_기타 (명)    26.320     17.04        0
39                  교육받지않이유_없음 (명)     9.870     6.816        0
40              교육받지않이유_모름/무응답 (명)     0.000         0        0
41                교육실제도움정도_사례수 (명)   441.000     324.0    241.0
42           교육실제도움정도_전혀 도움 안됨 (명)     2.646     1.296        0
43              교육실제도움정도_도움 안됨 (명)    22.491    10.044    1.928
44                 교육실제도움정도_보통 (명)    99.666    75.816   32.294
45               교육실제도움정도_도움 됨 (명)   287.973   227.772  194.969
46            교육실제도움정도_매우 도움 됨 (명)    28.224     8.424   11.809

In [20]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ind     47 non-null     object
 1   Y19     47 non-null     float64
 2   Y20     47 non-null     object
 3   Y21     47 non-null     object
dtypes: float64(1), object(3)
memory usage: 1.6+ KB

In [21]:
pdata.set_index('Ind')

                                     Y19       Y20      Y21
Ind
귀농귀촌 온라인 교육 이수여부_사례수 (명)        2081.000    2038.0   3000.0
귀농귀촌 온라인 교육 이수여부_이수 (명)          447.415    417.79      726
귀농귀촌 온라인 교육 이수여부_이수하지 않음 (명)    1633.585   1620.21     2274
귀농귀촌 오프라인 교육 이수여부_사례수 (명)       2081.000    2038.0   3000.0
귀농귀촌 오프라인 교육 이수여부_이수 (명)        1177.846   892.644     1275
귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (명)    903.154  1145.356     1725
귀농귀촌 인턴십 이수여부_사례수 (명)           2081.000    2038.0   3000.0
귀농귀촌 인턴십 이수여부_이수 (명)             310.069   228.256      504
귀농귀촌 인턴십 이수여부_이수하지 않음 (명)       1770.931  1809.744     2496
귀농귀촌교육개선점_사례수 (명)               2086.000    2028.0   3000.0
귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (명)      888.264   888.264     1215
귀농귀촌교육개선점_수준별 강좌 개설 (명)          321.244   336.648      603
귀농귀촌교육개선점_강사의 전문성 증대 (명)          93.870   150.072      249
귀농귀촌교육개선점_교육 비용 지원 (명)           129.332    77.064      147
귀농귀촌교육개선점_현장 실습 연계 강화 (명)        235.718   216.996      252
귀농귀촌교육개선점_교육 시간대 다양화 (명)         135.590     101.4      159
귀농귀촌교육개선점_지리적 접근성 확대 (명)         135.590   137.904      201
귀농귀촌교육개선점_온라인 교육 확대 (명)          102.214    97.344      177
귀농귀촌교육개선점_기타 (명)                   6.258         0        0
귀농귀촌교육개선점_없음 (명)                  18.774    16.224  #VALUE!
귀농귀촌교육개선점_모름/무응답 (명)               8.344     6.084  #VALUE!
귀농귀촌교육강화점_사례수 (명)               2086.000    2028.0   3000.0
귀농귀촌교육강화점_주거 및 전원생활 (명)          554.876   661.128      867
귀농귀촌교육강화점_귀촌창업 (명)               248.234   156.156      333
귀농귀촌교육강화점_관계형성 (명)               252.406    294.06      615
귀농귀촌교육강화점_텃밭 가꾸기 (명)             196.084   180.492      348
귀농귀촌교육강화점_영농교육 (명)               168.966   166.296      207
귀농귀촌교육강화점_농업농촌의 이해(기초소양) (명)     202.342   148.044      204
귀농귀촌교육강화점_제도,정책 (명)              435.974   387.348      426
귀농귀촌교육강화점_기타 (명)                   4.172     2.028        0
귀농귀촌교육강화점_없음 (명)                  16.688    26.364  #VALUE!
귀농귀촌교육강화점_모름/무응답 (명)               6.258     6.084  #VALUE!
교육받지않이유_사례수 (명)                 1645.000    1704.0   2759.0
교육받지않이유_교육에 대해 알지 못해서 (명)        845.530   736.128  954.614
교육받지않이유_시간이 없어서 (명)              343.805   449.856  731.135
교육받지않이유_적합한 과정(작목, 과목)이 없어 (명)   187.530   149.952  411.091
교육받지않이유_내용이 도움이 되지 않아서 (명)       225.365     340.8  637.329
교육받지않이유_교육비용 때문에 (명)               8.225     1.704   22.072
교육받지않이유_기타 (명)                    26.320     17.04        0
교육받지않이유_없음 (명)                     9.870     6.816  #VALUE!
교육받지않이유_모름/무응답 (명)                 0.000   #VALUE!  #VALUE!
교육실제도움정도_사례수 (명)                 441.000     324.0    241.0
교육실제도움정도_전혀 도움 안됨 (명)              2.646     1.296        0
교육실제도움정도_도움 안됨 (명)                22.491    10.044    1.928
교육실제도움정도_보통 (명)                   99.666    75.816   32.294
교육실제도움정도_도움 됨 (명)                287.973   227.772  194.969
교육실제도움정도_매우 도움 됨 (명)              28.224     8.424   11.809

In [22]:
df0 = pdata.replace('#VALUE!','0')
df0

                               Ind       Y19       Y20      Y21
0         귀농귀촌 온라인 교육 이수여부_사례수 (명)  2081.000    2038.0   3000.0
1          귀농귀촌 온라인 교육 이수여부_이수 (명)   447.415    417.79      726
2     귀농귀촌 온라인 교육 이수여부_이수하지 않음 (명)  1633.585   1620.21     2274
3        귀농귀촌 오프라인 교육 이수여부_사례수 (명)  2081.000    2038.0   3000.0
4         귀농귀촌 오프라인 교육 이수여부_이수 (명)  1177.846   892.644     1275
5    귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (명)   903.154  1145.356     1725
6            귀농귀촌 인턴십 이수여부_사례수 (명)  2081.000    2038.0   3000.0
7             귀농귀촌 인턴십 이수여부_이수 (명)   310.069   228.256      504
8        귀농귀촌 인턴십 이수여부_이수하지 않음 (명)  1770.931  1809.744     2496
9                귀농귀촌교육개선점_사례수 (명)  2086.000    2028.0   3000.0
10     귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (명)   888.264   888.264     1215
11         귀농귀촌교육개선점_수준별 강좌 개설 (명)   321.244   336.648      603
12        귀농귀촌교육개선점_강사의 전문성 증대 (명)    93.870   150.072      249
13          귀농귀촌교육개선점_교육 비용 지원 (명)   129.332    77.064      147
14       귀농귀촌교육개선점_현장 실습 연계 강화 (명)   235.718   216.996      252
15        귀농귀촌교육개선점_교육 시간대 다양화 (명)   135.590     101.4      159
16        귀농귀촌교육개선점_지리적 접근성 확대 (명)   135.590   137.904      201
17         귀농귀촌교육개선점_온라인 교육 확대 (명)   102.214    97.344      177
18                귀농귀촌교육개선점_기타 (명)     6.258         0        0
19                귀농귀촌교육개선점_없음 (명)    18.774    16.224        0
20            귀농귀촌교육개선점_모름/무응답 (명)     8.344     6.084        0
21               귀농귀촌교육강화점_사례수 (명)  2086.000    2028.0   3000.0
22         귀농귀촌교육강화점_주거 및 전원생활 (명)   554.876   661.128      867
23              귀농귀촌교육강화점_귀촌창업 (명)   248.234   156.156      333
24              귀농귀촌교육강화점_관계형성 (명)   252.406    294.06      615
25            귀농귀촌교육강화점_텃밭 가꾸기 (명)   196.084   180.492      348
26              귀농귀촌교육강화점_영농교육 (명)   168.966   166.296      207
27    귀농귀촌교육강화점_농업농촌의 이해(기초소양) (명)   202.342   148.044      204
28             귀농귀촌교육강화점_제도,정책 (명)   435.974   387.348      426
29                귀농귀촌교육강화점_기타 (명)     4.172     2.028        0
30                귀농귀촌교육강화점_없음 (명)    16.688    26.364        0
31            귀농귀촌교육강화점_모름/무응답 (명)     6.258     6.084        0
32                 교육받지않이유_사례수 (명)  1645.000    1704.0   2759.0
33       교육받지않이유_교육에 대해 알지 못해서 (명)   845.530   736.128  954.614
34             교육받지않이유_시간이 없어서 (명)   343.805   449.856  731.135
35  교육받지않이유_적합한 과정(작목, 과목)이 없어 (명)   187.530   149.952  411.091
36      교육받지않이유_내용이 도움이 되지 않아서 (명)   225.365     340.8  637.329
37            교육받지않이유_교육비용 때문에 (명)     8.225     1.704   22.072
38                  교육받지않이유_기타 (명)    26.320     17.04        0
39                  교육받지않이유_없음 (명)     9.870     6.816        0
40              교육받지않이유_모름/무응답 (명)     0.000         0        0
41                교육실제도움정도_사례수 (명)   441.000     324.0    241.0
42           교육실제도움정도_전혀 도움 안됨 (명)     2.646     1.296        0
43              교육실제도움정도_도움 안됨 (명)    22.491    10.044    1.928
44                 교육실제도움정도_보통 (명)    99.666    75.816   32.294
45               교육실제도움정도_도움 됨 (명)   287.973   227.772  194.969
46            교육실제도움정도_매우 도움 됨 (명)    28.224     8.424   11.809

In [28]:
df1 = df0.round(0).astype({'Y19':int,
                            'Y20':int,
                            'Y21':int})
df1

                               Ind   Y19   Y20   Y21
0         귀농귀촌 온라인 교육 이수여부_사례수 (명)  2081  2038  3000
1          귀농귀촌 온라인 교육 이수여부_이수 (명)   447   417   726
2     귀농귀촌 온라인 교육 이수여부_이수하지 않음 (명)  1634  1620  2274
3        귀농귀촌 오프라인 교육 이수여부_사례수 (명)  2081  2038  3000
4         귀농귀촌 오프라인 교육 이수여부_이수 (명)  1178   892  1275
5    귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (명)   903  1145  1725
6            귀농귀촌 인턴십 이수여부_사례수 (명)  2081  2038  3000
7             귀농귀촌 인턴십 이수여부_이수 (명)   310   228   504
8        귀농귀촌 인턴십 이수여부_이수하지 않음 (명)  1771  1809  2496
9                귀농귀촌교육개선점_사례수 (명)  2086  2028  3000
10     귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (명)   888   888  1215
11         귀농귀촌교육개선점_수준별 강좌 개설 (명)   321   336   603
12        귀농귀촌교육개선점_강사의 전문성 증대 (명)    94   150   249
13          귀농귀촌교육개선점_교육 비용 지원 (명)   129    77   147
14       귀농귀촌교육개선점_현장 실습 연계 강화 (명)   236   216   252
15        귀농귀촌교육개선점_교육 시간대 다양화 (명)   136   101   159
16        귀농귀촌교육개선점_지리적 접근성 확대 (명)   136   137   201
17         귀농귀촌교육개선점_온라인 교육 확대 (명)   102    97   177
18                귀농귀촌교육개선점_기타 (명)     6     0     0
19                귀농귀촌교육개선점_없음 (명)    19    16     0
20            귀농귀촌교육개선점_모름/무응답 (명)     8     6     0
21               귀농귀촌교육강화점_사례수 (명)  2086  2028  3000
22         귀농귀촌교육강화점_주거 및 전원생활 (명)   555   661   867
23              귀농귀촌교육강화점_귀촌창업 (명)   248   156   333
24              귀농귀촌교육강화점_관계형성 (명)   252   294   615
25            귀농귀촌교육강화점_텃밭 가꾸기 (명)   196   180   348
26              귀농귀촌교육강화점_영농교육 (명)   169   166   207
27    귀농귀촌교육강화점_농업농촌의 이해(기초소양) (명)   202   148   204
28             귀농귀촌교육강화점_제도,정책 (명)   436   387   426
29                귀농귀촌교육강화점_기타 (명)     4     2     0
30                귀농귀촌교육강화점_없음 (명)    17    26     0
31            귀농귀촌교육강화점_모름/무응답 (명)     6     6     0
32                 교육받지않이유_사례수 (명)  1645  1704  2759
33       교육받지않이유_교육에 대해 알지 못해서 (명)   846   736   954
34             교육받지않이유_시간이 없어서 (명)   344   449   731
35  교육받지않이유_적합한 과정(작목, 과목)이 없어 (명)   188   149   411
36      교육받지않이유_내용이 도움이 되지 않아서 (명)   225   340   637
37            교육받지않이유_교육비용 때문에 (명)     8     1    22
38                  교육받지않이유_기타 (명)    26    17     0
39                  교육받지않이유_없음 (명)    10     6     0
40              교육받지않이유_모름/무응답 (명)     0     0     0
41                교육실제도움정도_사례수 (명)   441   324   241
42           교육실제도움정도_전혀 도움 안됨 (명)     3     1     0
43              교육실제도움정도_도움 안됨 (명)    22    10     1
44                 교육실제도움정도_보통 (명)   100    75    32
45               교육실제도움정도_도움 됨 (명)   288   227   194
46            교육실제도움정도_매우 도움 됨 (명)    28     8    11

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ind     47 non-null     object
 1   Y19     47 non-null     int64
 2   Y20     47 non-null     int64
 3   Y21     47 non-null     int64
dtypes: int64(3), object(1)
memory usage: 1.6+ KB