<a href="https://colab.research.google.com/github/limyerin/contest/blob/main/test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#테스트

In [74]:
from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [75]:
data= pd.read_excel("/content/drive/MyDrive/data/data1.xlsx",engine='openpyxl')
data

,ind,y19,y20,y21,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,귀농귀촌 온라인 교육 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,NaN,교육이수여부_
1,귀농귀촌 온라인 교육 이수여부_이수 (%),21.5,20.5,24.2,NaN,NaN,NaN
2,귀농귀촌 온라인 교육 이수여부_이수하지 않음 (%),78.5,79.5,75.8,NaN,NaN,NaN
3,귀농귀촌 오프라인 교육 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,NaN,NaN
4,귀농귀촌 오프라인 교육 이수여부_이수 (%),56.6,43.8,42.5,NaN,NaN,NaN
5,귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (%),43.4,56.2,57.5,NaN,NaN,NaN
6,귀농귀촌 인턴십 이수여부_사례수 (명),2081.0,2038.0,3000.0,NaN,NaN,NaN
7,귀농귀촌 인턴십 이수여부_이수 (%),14.9,11.2,16.8,NaN,NaN,NaN
8,귀농귀촌 인턴십 이수여부_이수하지 않음 (%),85.1,88.8,83.2,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,귀농귀촌교육개선점_사례수 (명),2086.0,2028.0,3000.0,NaN,NaN,귀농귀촌교육개선점_
11,귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (%),43.2,43.8,40.5,NaN,NaN,NaN
12,귀농귀촌교육개선점_수준별 강좌 개설 (%),15.4,16.6,20.1,NaN,NaN,NaN
13,귀농귀촌교육개선점_강사의 전문성 증대 (%),4.5,7.4,8.3,NaN,NaN,NaN
14,귀농귀촌교육개선점_교육 비용 지원 (%),6.2,3.8,4.9,NaN,NaN,NaN
15,귀농귀촌교육개선점_현장 실습 연계 강화 (%),11.3,10.7,8.4,NaN,NaN,NaN
16,귀농귀촌교육개선점_교육 시간대 다양화 (%),6.5,5.0,5.3,NaN,NaN,NaN
17,귀농귀촌교육개선점_지리적 접근성 확대 (%),6.5,6.8,6.7,NaN,NaN,NaN
18,귀농귀촌교육개선점_온라인 교육 확대 (%),4.9,4.8,5.9,NaN,NaN,NaN
19,귀농귀촌교육개선점_기타 (%),0.3,0.0,0.0,NaN,NaN,NaN
20,귀농귀촌교육개선점_없음 (%),0.9,0.8,-,NaN,NaN,NaN
21,귀농귀촌교육개선점_모름/무응답 (%),0.4,0.3,-,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,귀농귀촌교육강화점_사례수 (명),2086.0,2028.0,3000.0,NaN,NaN,귀농귀촌교육강화점_
24,귀농귀촌교육강화점_주거 및 전원생활 (%),26.6,32.6,28.9,NaN,NaN,NaN
25,귀농귀촌교육강화점_귀촌창업 (%),11.9,7.7,11.1,NaN,NaN,NaN
26,귀농귀촌교육강화점_관계형성 (%),12.1,14.5,20.5,NaN,NaN,NaN
27,귀농귀촌교육강화점_텃밭 가꾸기 (%),9.4,8.9,11.6,NaN,NaN,NaN
28,귀농귀촌교육강화점_영농교육 (%),8.1,8.2,6.9,NaN,NaN,NaN
29,귀농귀촌교육강화점_농업농촌의 이해(기초소양) (%),9.7,7.3,6.8,NaN,NaN,NaN
30,"귀농귀촌교육강화점_제도,정책 (%)",20.9,19.1,14.2,NaN,NaN,NaN
31,귀농귀촌교육강화점_기타 (%),0.2,0.1,0.0,NaN,NaN,NaN
32,귀농귀촌교육강화점_없음 (%),0.8,1.3,-,NaN,NaN,NaN
33,귀농귀촌교육강화점_모름/무응답 (%),0.3,0.3,-,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,교육받지않이유_사례수 (명),1645.0,1704.0,2759.0,NaN,NaN,교육받지않이유_
36,교육받지않이유_교육에 대해 알지 못해서 (%),51.4,43.2,34.6,NaN,NaN,NaN
37,교육받지않이유_시간이 없어서 (%),20.9,26.4,26.5,NaN,NaN,NaN
38,"교육받지않이유_적합한 과정(작목, 과목)이 없어 (%)",11.4,8.8,14.9,NaN,NaN,NaN
39,교육받지않이유_내용이 도움이 되지 않아서 (%),13.7,20.0,23.1,NaN,NaN,NaN
40,교육받지않이유_교육비용 때문에 (%),0.5,0.1,0.8,NaN,NaN,NaN
41,교육받지않이유_기타 (%),1.6,1.0,0.0,NaN,NaN,NaN
42,교육받지않이유_없음 (%),0.6,0.4,-,NaN,NaN,NaN
43,교육받지않이유_모름/무응답 (%),0.0,-,-,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,교육실제도움정도_사례수 (명),441.0,324.0,241.0,NaN,NaN,교육실제도움정도_
46,교육실제도움정도_전혀 도움 안됨 (%),0.6,0.4,0.0,NaN,NaN,NaN
47,교육실제도움정도_도움 안됨 (%),5.1,3.1,0.8,NaN,NaN,NaN
48,교육실제도움정도_보통 (%),22.6,23.4,13.4,NaN,NaN,NaN
49,교육실제도움정도_도움 됨 (%),65.3,70.3,80.9,NaN,NaN,NaN
50,교육실제도움정도_매우 도움 됨 (%),6.4,2.6,4.9,NaN,NaN,NaN

In [77]:
data1=data.set_index("ind")
data1.columns

Index(['y19', 'y20', 'y21', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'], dtype='object')

In [78]:
data1.drop(['Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'],axis=1,inplace=True)

In [79]:
data1

                                   y19     y20     y21
ind
귀농귀촌 온라인 교육 이수여부_사례수 (명)        2081.0  2038.0  3000.0
귀농귀촌 온라인 교육 이수여부_이수 (%)           21.5    20.5    24.2
귀농귀촌 온라인 교육 이수여부_이수하지 않음 (%)      78.5    79.5    75.8
귀농귀촌 오프라인 교육 이수여부_사례수 (명)       2081.0  2038.0  3000.0
귀농귀촌 오프라인 교육 이수여부_이수 (%)          56.6    43.8    42.5
귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (%)     43.4    56.2    57.5
귀농귀촌 인턴십 이수여부_사례수 (명)           2081.0  2038.0  3000.0
귀농귀촌 인턴십 이수여부_이수 (%)              14.9    11.2    16.8
귀농귀촌 인턴십 이수여부_이수하지 않음 (%)         85.1    88.8    83.2
NaN                                NaN     NaN     NaN
귀농귀촌교육개선점_사례수 (명)               2086.0  2028.0  3000.0
귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (%)       43.2    43.8    40.5
귀농귀촌교육개선점_수준별 강좌 개설 (%)           15.4    16.6    20.1
귀농귀촌교육개선점_강사의 전문성 증대 (%)           4.5     7.4     8.3
귀농귀촌교육개선점_교육 비용 지원 (%)             6.2     3.8     4.9
귀농귀촌교육개선점_현장 실습 연계 강화 (%)         11.3    10.7     8.4
귀농귀촌교육개선점_교육 시간대 다양화 (%)           6.5     5.0     5.3
귀농귀촌교육개선점_지리적 접근성 확대 (%)           6.5     6.8     6.7
귀농귀촌교육개선점_온라인 교육 확대 (%)            4.9     4.8     5.9
귀농귀촌교육개선점_기타 (%)                   0.3     0.0     0.0
귀농귀촌교육개선점_없음 (%)                   0.9     0.8       -
귀농귀촌교육개선점_모름/무응답 (%)               0.4     0.3       -
NaN                                NaN     NaN     NaN
귀농귀촌교육강화점_사례수 (명)               2086.0  2028.0  3000.0
귀농귀촌교육강화점_주거 및 전원생활 (%)           26.6    32.6    28.9
귀농귀촌교육강화점_귀촌창업 (%)                11.9     7.7    11.1
귀농귀촌교육강화점_관계형성 (%)                12.1    14.5    20.5
귀농귀촌교육강화점_텃밭 가꾸기 (%)               9.4     8.9    11.6
귀농귀촌교육강화점_영농교육 (%)                 8.1     8.2     6.9
귀농귀촌교육강화점_농업농촌의 이해(기초소양) (%)       9.7     7.3     6.8
귀농귀촌교육강화점_제도,정책 (%)               20.9    19.1    14.2
귀농귀촌교육강화점_기타 (%)                   0.2     0.1     0.0
귀농귀촌교육강화점_없음 (%)                   0.8     1.3       -
귀농귀촌교육강화점_모름/무응답 (%)               0.3     0.3       -
NaN                                NaN     NaN     NaN
교육받지않이유_사례수 (명)                 1645.0  1704.0  2759.0
교육받지않이유_교육에 대해 알지 못해서 (%)         51.4    43.2    34.6
교육받지않이유_시간이 없어서 (%)               20.9    26.4    26.5
교육받지않이유_적합한 과정(작목, 과목)이 없어 (%)    11.4     8.8    14.9
교육받지않이유_내용이 도움이 되지 않아서 (%)        13.7    20.0    23.1
교육받지않이유_교육비용 때문에 (%)               0.5     0.1     0.8
교육받지않이유_기타 (%)                     1.6     1.0     0.0
교육받지않이유_없음 (%)                     0.6     0.4       -
교육받지않이유_모름/무응답 (%)                 0.0       -       -
NaN                                NaN     NaN     NaN
교육실제도움정도_사례수 (명)                 441.0   324.0   241.0
교육실제도움정도_전혀 도움 안됨 (%)              0.6     0.4     0.0
교육실제도움정도_도움 안됨 (%)                 5.1     3.1     0.8
교육실제도움정도_보통 (%)                   22.6    23.4    13.4
교육실제도움정도_도움 됨 (%)                 65.3    70.3    80.9
교육실제도움정도_매우 도움 됨 (%)               6.4     2.6     4.9

In [81]:
data1['y19']

ind
귀농귀촌 온라인 교육 이수여부_사례수 (명)          2081.0
귀농귀촌 온라인 교육 이수여부_이수 (%)             21.5
귀농귀촌 온라인 교육 이수여부_이수하지 않음 (%)        78.5
귀농귀촌 오프라인 교육 이수여부_사례수 (명)         2081.0
귀농귀촌 오프라인 교육 이수여부_이수 (%)            56.6
귀농귀촌 오프라인 교육 이수여부_이수하지 않음 (%)       43.4
귀농귀촌 인턴십 이수여부_사례수 (명)             2081.0
귀농귀촌 인턴십 이수여부_이수 (%)                14.9
귀농귀촌 인턴십 이수여부_이수하지 않음 (%)           85.1
NaN                                  NaN
귀농귀촌교육개선점_사례수 (명)                 2086.0
귀농귀촌교육개선점_다양한 교육 콘텐츠 개발 (%)         43.2
귀농귀촌교육개선점_수준별 강좌 개설 (%)             15.4
귀농귀촌교육개선점_강사의 전문성 증대 (%)             4.5
귀농귀촌교육개선점_교육 비용 지원 (%)               6.2
귀농귀촌교육개선점_현장 실습 연계 강화 (%)           11.3
귀농귀촌교육개선점_교육 시간대 다양화 (%)             6.5
귀농귀촌교육개선점_지리적 접근성 확대 (%)             6.5
귀농귀촌교육개선점_온라인 교육 확대 (%)              4.9
귀농귀촌교육개선점_기타 (%)                     0.3
귀농귀촌교육개선점_없음 (%)                     0.9
귀농귀촌교육개선점_모름/무응답 (%)                 0.4
NaN                                  NaN
귀농귀촌교육강화점_사례수 (명)                 2086.0
귀농귀촌교육강화점_주거 및 전원생활 (%)             26.6
귀농귀촌교육강화점_귀촌창업 (%)                  11.9
귀농귀촌교육강화점_관계형성 (%)                  12.1
귀농귀촌교육강화점_텃밭 가꾸기 (%)                 9.4
귀농귀촌교육강화점_영농교육 (%)                   8.1
귀농귀촌교육강화점_농업농촌의 이해(기초소양) (%)         9.7
귀농귀촌교육강화점_제도,정책 (%)                 20.9
귀농귀촌교육강화점_기타 (%)                     0.2
귀농귀촌교육강화점_없음 (%)                     0.8
귀농귀촌교육강화점_모름/무응답 (%)                 0.3
NaN                                  NaN
교육받지않이유_사례수 (명)                   1645.0
교육받지않이유_교육에 대해 알지 못해서 (%)           51.4
교육받지않이유_시간이 없어서 (%)                 20.9
교육받지않이유_적합한 과정(작목, 과목)이 없어 (%)      11.4
교육받지않이유_내용이 도움이 되지 않아서 (%)          13.7
교육받지않이유_교육비용 때문에 (%)                 0.5
교육받지않이유_기타 (%)                       1.6
교육받지않이유_없음 (%)                       0.6
교육받지않이유_모름/무응답 (%)                   0.0
NaN                                  NaN
교육실제도움정도_사례수 (명)                   441.0
교육실제도움정도_전혀 도움 안됨 (%)                0.6
교육실제도움정도_도움 안됨 (%)                   5.1
교육실제도움정도_보통 (%)                     22.6
교육실제도움정도_도움 됨 (%)                   65.3
교육실제도움정도_매우 도움 됨 (%)                 6.4
Name: y19, dtype: float64

In [88]:
len(data1[:]['y19'])

51

In [91]:
data[0:1]['y19']

0    2081.0
Name: y19, dtype: float64

[아래 코드]
100이상이면 사례수(명)으로 파악해서 백분율(100이하) 와 곱해주는 반복문 만들려고 시도.
반복문 진행하다가 다시 100이상의 수를 만나면 다시 곱해서 구하는 방식 생각.

In [101]:
for i in range(1,51):
  if (data1[i-1:i]['y19']>=100):
    j=i
    n=0
    while((data1[j:j+1]['y19']<100) == True) :
      n+=1
      re= data1[i-1:i]['y19']*(data1[j:j+1]['y19'])
      data1.replace(data1[j:j+1]['y19'], re)
      j+=1
    
    i+=n

  if (data1[i-1:i]['y19'] == np.NaN):
      pass

  else:
      pass

ValueError: ignored

In [105]:
for i in range(1,51):
  i+=1
  print(i)
  while (data1[i-1:i]['y19']>=100):
    print(data1[i-1:i]['y19'])

2

ValueError: ignored

AttributeError: ignored